// In Typescript you cn create and initialize arrays using various approaches
// Using square bracket...
// const numbers:number[] = [1,2,3,4,5,6];
// Using the Array Constructor...
// const numbers:number[] = new Array(1,2,3,4,5,6);
// Using the Array.of methos....
var names = Array.of("Ifra", "Nisha", "Tehreem");
console.log(names[0]);
